version: '3.8'
services:
  baby-tracker:
    container_name: baby_tracker
    image: "ghcr.io/xigemax/baby_tracker:latest"
    ports:
      - "8964:5000"
    volumes:
      - ./data:/app/data
    environment:
      - FLASK_ENV=production
      - TZ=Asia/Shanghai
    restart: unless-stopped
